#!/usr/bin/env node
// Imports every background pattern from import/bgs/*.aseprite into
// renderer/background.js, keyed by id so the settings window can offer a
// picker (SPEC.md §7 `background`).
//
//   npm run bgs                  # default source dir below, all *.aseprite
//   npm run bgs -- <dir>
//
// bg-template.aseprite is a starting point for drawing a new background, not
// a background itself, so it is always skipped.
//
// Re-run after adding or editing a sprite in Aseprite; nothing else needs
// touching. Requires Aseprite installed (its CLI does the decoding of its
// own format).
//
// Each source is a single frame, one colour on nothing, exactly CANVAS_W
// wide. Height is whatever the artist drew — the widget only ever shows the
// top of it (see renderer/background.js), so there's nothing to validate
// there.

'use strict';

const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const { readPng } = require('./read-png');

const ASEPRITE = '/Applications/Aseprite.app/Contents/MacOS/aseprite';
const DEFAULT_DIR = path.join(__dirname, '..', 'import', 'bgs');
const TEMPLATE_NAME = 'bg-template';
const CANVAS_W = 118; // renderer/widget.js CANVAS_W — kept in sync by hand, nothing to import it from

const args = process.argv.slice(2);
const srcDir = args[0] || DEFAULT_DIR;

if (!fs.existsSync(ASEPRITE)) {
  console.error('Aseprite not found at ' + ASEPRITE + '\nInstall it, or edit renderer/background.js by hand.');
  process.exit(1);
}

const names = fs.readdirSync(srcDir)
  .filter((f) => f.endsWith('.aseprite'))
  .map((f) => f.slice(0, -'.aseprite'.length))
  .filter((name) => name !== TEMPLATE_NAME)
  .sort();

if (names.length === 0) {
  console.error(`no background .aseprite files in ${srcDir} (besides ${TEMPLATE_NAME}.aseprite)`);
  process.exit(1);
}

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pomoppi-bgs-'));
const backgrounds = [];

for (const name of names) {
  const src = path.join(srcDir, name + '.aseprite');
  const sheet = path.join(tmp, name + '.png');
  execFileSync(ASEPRITE, ['-b', src, '--sheet', sheet], { stdio: 'pipe' });

  const { w, h, alpha } = readPng(sheet);
  if (w !== CANVAS_W) {
    console.error(`${name}: expected ${CANVAS_W}px wide (the canvas width), got ${w}px`);
    process.exit(1);
  }

  const grid = [];
  for (let y = 0; y < h; y++) {
    let row = '';
    for (let x = 0; x < w; x++) row += alpha(x, y) > 127 ? '#' : '.';
    grid.push(row);
  }
  const ink = grid.join('').split('').filter((c) => c === '#').length;
  // 'bg-scacchi' -> id 'scacchi', name 'Scacchi'
  const id = name.replace(/^bg-/, '');
  const label = id.charAt(0).toUpperCase() + id.slice(1);
  backgrounds.push({ id, name: label, grid });
  console.log(`${name.padEnd(16)} ${w}x${h}, ${ink} ink px`);
}

fs.rmSync(tmp, { recursive: true, force: true });

const body = backgrounds.map((b) =>
  `  ${b.id}: {\n` +
  `    name: '${b.name}',\n` +
  `    pattern: [\n` +
  b.grid.map((r) => `      '${r}',`).join('\n') +
  `\n    ],\n  },`
).join('\n');
const ids = backgrounds.map((b) => `'${b.id}'`).join(', ');

const out = `// background.js — GENERATED by tools/import-bgs.js. Do not edit by hand.
//
// Source: ${path.relative(path.join(__dirname, '..'), srcDir)}/*.aseprite (bg-template.aseprite excluded)
// Re-import after editing or adding a sprite in Aseprite:  npm run bgs
//
// Each pattern is drawn behind everything else at the canvas's top-left
// (0,0), keyed by id (BACKGROUND_IDS gives display order). Shorter than the
// full canvas height on purpose: the frame is opaque over most of its own
// area, so a pattern only ever shows through the outer margin and the
// frame's scalloped notches near the top. '#' ink, '.' clear.

(function () {
const BACKGROUNDS = {
${body}
};
const BACKGROUND_IDS = [${ids}];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { BACKGROUNDS, BACKGROUND_IDS };
}
if (typeof window !== 'undefined') {
  window.BACKGROUNDS = BACKGROUNDS;
  window.BACKGROUND_IDS = BACKGROUND_IDS;
}
})();
`;

const dest = path.join(__dirname, '..', 'renderer', 'background.js');
fs.writeFileSync(dest, out);
console.log('wrote ' + path.relative(path.join(__dirname, '..'), dest) + ' (' + out.length + ' bytes)');
