#!/usr/bin/env node
// refresh-sounds.js — the one command that keeps the app's chime sounds in
// sync with their sources: re-imports Sounds/import/chimes/*/ WAV packs,
// then regenerates Sources/PomoppiSprites/Sounds.generated.swift from
// whatever was found. Audio and pixel art are different enough pipelines to
// deserve their own top-level command rather than folding into
// refresh-art.js.
//
//   node refresh-sounds
//
// Sounds.generated.swift is always rewritten last, regardless of what
// changed, so it's never left stale relative to Sounds/import/chimes/*/.
'use strict';

const fs = require('fs');
const path = require('path');

const { importChimes } = require('./Sounds/tools/import-chimes');
const { SAMPLE_RATE, BITS_PER_SAMPLE, CHANNELS } = require('./Sounds/tools/wav');

const { chimeIDs, chimes } = importChimes();

// --- keep Sources/PomoppiCore/Settings.swift's chimeIDs in sync -----------
//
// Same trick refresh-art.js's own syncIDs() uses for friendIDs/backgroundIDs:
// PomoppiCore intentionally has zero dependency on generated art (or sound)
// data, so this regex-rewrites just the one array literal in Settings.swift
// rather than making PomoppiCore depend on PomoppiSprites. Unlike the art
// version, this line doesn't exist on a fresh checkout yet, so the first
// run inserts it (right after backgroundIDs, the other roster arrays'
// neighbour) instead of only being able to replace an existing match; every
// run after that is a plain sync/replace like the original.
//
// Unlike friendIDs/backgroundIDs (plain alphabetical), chimeIDs' order is
// meaningful — importChimes() already put it in picker order (classic
// first, the rest alphabetical) — so this takes `ids` as given rather than
// re-sorting it.
function syncIDs(fieldName, ids) {
  const ordered = [...ids];
  const line = (indent) => `${indent}public static let ${fieldName} = [${ordered.map((id) => JSON.stringify(id)).join(', ')}]`;

  const dest = path.join(__dirname, 'Sources/PomoppiCore/Settings.swift');
  const before = fs.readFileSync(dest, 'utf8');
  const re = new RegExp(`^(\\s*)public static let ${fieldName} = \\[[^\\]]*\\]`, 'm');
  const match = before.match(re);

  if (match) {
    const previous = [...match[0].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
    const added = ordered.filter((id) => !previous.includes(id));
    const removed = previous.filter((id) => !ordered.includes(id));
    const next = line(match[1]);
    if (next !== match[0]) {
      fs.writeFileSync(dest, before.replace(re, next));
      console.log(`\nSettings.swift ${fieldName}: ${added.length ? '+' + added.join(', +') + ' ' : ''}${removed.length ? '-' + removed.join(', -') : ''}`.trim());
    }
    return;
  }

  const bgRe = /^(\s*)public static let backgroundIDs = \[[^\]]*\]\n/m;
  const bgMatch = before.match(bgRe);
  if (!bgMatch) {
    console.error(`could not find "public static let backgroundIDs = [...]" in Settings.swift to insert ${fieldName} after`);
    process.exit(1);
  }
  fs.writeFileSync(dest, before.replace(bgRe, bgMatch[0] + line(bgMatch[1]) + '\n'));
  console.log(`\nSettings.swift: inserted ${fieldName} = [${ordered.join(', ')}]`);
}

syncIDs('chimeIDs', chimeIDs);

// --- regenerate Sources/PomoppiSprites/Sounds.generated.swift -------------
//
// Always built from whatever importChimes() just read off disk, never
// hand-transcribed data, same "read the live source, not a cache" contract
// as refresh-art.js's own Sprites.generated.swift step.

function swiftByteArray(buf) {
  return '[' + Array.from(buf).join(', ') + ']';
}

const chimeEntries = chimeIDs.map((id) =>
  `        ${JSON.stringify(id)}: Chime(\n` +
  `            focusEnd: ${swiftByteArray(chimes[id].focusEnd)},\n` +
  `            breakEnd: ${swiftByteArray(chimes[id].breakEnd)}),`
).join('\n');

const output = `// Sounds.generated.swift — GENERATED by refresh-sounds.js.
// Do not hand-edit. Source: Sounds/import/chimes/*/focus-end.wav,
// break-end.wav. Re-run \`node refresh-sounds\` after those change.
public enum GeneratedSounds {
    public static let sampleRate = ${SAMPLE_RATE}
    public static let bitsPerSample = ${BITS_PER_SAMPLE}
    public static let channels = ${CHANNELS}

    public struct Chime {
        public let focusEnd: [UInt8]
        public let breakEnd: [UInt8]
    }
    public static let chimeIDs: [String] = [${chimeIDs.map((id) => JSON.stringify(id)).join(', ')}]
    public static let chimes: [String: Chime] = [
${chimeEntries}
    ]
}
`;

const outPath = path.join(__dirname, 'Sources/PomoppiSprites/Sounds.generated.swift');
fs.writeFileSync(outPath, output);
console.log(`wrote ${outPath} (${output.length} bytes)`);
