#!/usr/bin/env node
// generate-sprites.js — reads the real Electron art data (renderer/sprites.js,
// renderer/friends.js via sprites.js, renderer/background.js) and emits
// native/Sources/PomoppiSprites/Sprites.generated.swift.
//
// Only what Phase 1 renders ships here: the 5 button icons, the ZZZ
// break-sleep frames, one default friend's frames, and one default
// background's pattern. To widen the roster later, add ids to
// FRIEND_IDS_TO_EXPORT / BACKGROUND_IDS_TO_EXPORT below and re-run this
// script — it always reads the live JS files, never hand-transcribed data.
'use strict';

const fs = require('fs');
const path = require('path');

const SPRITES = require(path.join(__dirname, '../../renderer/sprites.js'));
const { BACKGROUNDS, BACKGROUND_IDS } = require(path.join(__dirname, '../../renderer/background.js'));

// The full roster — every friend/background PomoppiSettings' own validation
// already accepts (see PomoppiCore/Settings.swift's friendIDs/backgroundIDs)
// now actually has Swift art data to render, not just a name that falls back
// to the default.
const FRIEND_IDS_TO_EXPORT = SPRITES.FRIEND_IDS;
const BACKGROUND_IDS_TO_EXPORT = BACKGROUND_IDS;
const DEFAULT_FRIEND_ID = 'namidappi';
const DEFAULT_BACKGROUND_ID = 'scacchi';

for (const id of FRIEND_IDS_TO_EXPORT) {
  if (!SPRITES.FRIENDS[id]) throw new Error(`Unknown friend id: ${id}`);
}
for (const id of BACKGROUND_IDS_TO_EXPORT) {
  if (!BACKGROUNDS[id]) throw new Error(`Unknown background id: ${id}`);
}

function swiftStringLiteral(str) {
  return JSON.stringify(str);
}

function swiftStringArray(rows, indent) {
  const pad = '    '.repeat(indent);
  const items = rows.map((r) => pad + '    ' + swiftStringLiteral(r)).join(',\n');
  return `[\n${items}\n${pad}]`;
}

function swiftStringArrayOfArrays(arrays, indent) {
  const pad = '    '.repeat(indent);
  const items = arrays.map((rows) => pad + '    ' + swiftStringArray(rows, indent + 1)).join(',\n');
  return `[\n${items}\n${pad}]`;
}

const iconEntries = Object.entries(SPRITES.ICONS)
  .map(([name, rows]) => `        ${swiftStringLiteral(name)}: ${swiftStringArray(rows, 2)},`)
  .join('\n');

const zzzFrameEntries = SPRITES.ZZZ_FRAMES
  .map((f) => `        ZzzFrame(grid: ${swiftStringArray(f.grid, 2)}, dx: ${f.dx}, dy: ${f.dy}),`)
  .join('\n');

const friendEntries = FRIEND_IDS_TO_EXPORT
  .map((id) => `        ${swiftStringLiteral(id)}: ${swiftStringArrayOfArrays(SPRITES.FRIENDS[id].frames, 2)},`)
  .join('\n');

const backgroundEntries = BACKGROUND_IDS_TO_EXPORT
  .map((id) => `        ${swiftStringLiteral(id)}: ${swiftStringArray(BACKGROUNDS[id].pattern, 2)},`)
  .join('\n');

const trayFrameEntries = SPRITES.TRAY_FRAMES
  .map((frame) => `        ${swiftStringArray(frame, 2)},`)
  .join('\n');

const output = `// Sprites.generated.swift — GENERATED by native/Scripts/generate-sprites.js.
// Do not hand-edit. Source: renderer/sprites.js, renderer/friends.js,
// renderer/background.js. Re-run \`node native/Scripts/generate-sprites.js\`
// after those change.
public enum GeneratedSprites {
    public static let iconSize = ${SPRITES.ICON_SIZE}
    public static let icons: [String: [String]] = [
${iconEntries}
    ]

    public struct ZzzFrame {
        public let grid: [String]
        public let dx: Int
        public let dy: Int
    }
    public static let zzz: [String] = ${swiftStringArray(SPRITES.ZZZ, 1)}
    public static let zzzFrames: [ZzzFrame] = [
${zzzFrameEntries}
    ]

    public static let friendWidth = ${SPRITES.FRIEND_W}
    public static let friendHeight = ${SPRITES.FRIEND_H}
    public static let defaultFriendID = ${swiftStringLiteral(DEFAULT_FRIEND_ID)}
    // [friend id: frames], each frame ${SPRITES.FRIEND_H} rows of ${SPRITES.FRIEND_W} characters.
    public static let friendFrames: [String: [[String]]] = [
${friendEntries}
    ]

    public static let defaultBackgroundID = ${swiftStringLiteral(DEFAULT_BACKGROUND_ID)}
    public static let backgroundPatterns: [String: [String]] = [
${backgroundEntries}
    ]

    // Menu-bar art, 16x16, '1'/'0' grids like icons above. One entry per
    // renderer/sprites.js TRAY_FRAMES element; the tray animates by cycling
    // through them (see TrayController).
    public static let trayFrames: [[String]] = [
${trayFrameEntries}
    ]
}
`;

const outPath = path.join(__dirname, '../Sources/PomoppiSprites/Sprites.generated.swift');
fs.writeFileSync(outPath, output);
console.log(`Wrote ${outPath}`);
