// Strings.generated.swift — GENERATED by refresh-strings.js.
// Do not hand-edit. Source: Localization/*.json. Re-run
// `node refresh-strings` after those change.
enum GeneratedStrings {
    static let languageIDs: [String] = ["en"]

    static let tables: [String: [String: String]] = [
        "en": table_en,
    ]

    static let table_en: [String: String] = [
        "language.name": "English",
    ]
}
