#!/usr/bin/env node
// Imports friend sprites from .aseprite files into renderer/friends.js.
//
//   npm run friends              # default source directory below
//   npm run friends -- <dir> [...names]
//
// Re-run after editing a sprite in Aseprite; nothing else needs touching.
// Requires Aseprite installed (its CLI does the decoding of its own format).

const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const { readPng } = require('./read-png');

const ASEPRITE = '/Applications/Aseprite.app/Contents/MacOS/aseprite';
const DEFAULT_DIR = path.join(__dirname, '..', 'import', 'friends');
const DEFAULT_FRIENDS = ['Namidappi', 'Onanippi', 'Gemuppin', 'Jankuppin', 'Utsupon'];
const CELL = 32;

// --- import -----------------------------------------------------------------

const args = process.argv.slice(2);
const srcDir = args[0] || DEFAULT_DIR;
const names = args.length > 1 ? args.slice(1) : DEFAULT_FRIENDS;

if (!fs.existsSync(ASEPRITE)) {
  console.error('Aseprite not found at ' + ASEPRITE + '\nInstall it, or edit renderer/friends.js by hand.');
  process.exit(1);
}

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pomoppi-friends-'));
const friends = [];

for (const name of names) {
  const src = path.join(srcDir, name + '.aseprite');
  if (!fs.existsSync(src)) {
    console.error('missing: ' + src);
    process.exit(1);
  }
  const sheet = path.join(tmp, name + '.png');
  execFileSync(ASEPRITE, ['-b', src, '--sheet', sheet], { stdio: 'pipe' });

  const { w, h, alpha } = readPng(sheet);
  if (h !== CELL || w % CELL !== 0) {
    console.error(`${name}: expected a ${CELL}px-tall sheet in ${CELL}px frames, got ${w}x${h}`);
    process.exit(1);
  }

  const frames = [];
  for (let f = 0; f < w / CELL; f++) {
    const grid = [];
    for (let y = 0; y < CELL; y++) {
      let row = '';
      for (let x = 0; x < CELL; x++) row += alpha(f * CELL + x, y) > 127 ? '#' : '.';
      grid.push(row);
    }
    frames.push(grid);
  }
  const ink = frames[0].join('').split('').filter((c) => c === '#').length;
  friends.push({ id: name.toLowerCase(), name, frames });
  console.log(`${name.padEnd(12)} ${frames.length} frame(s), ${ink} ink px in frame 0`);
}

fs.rmSync(tmp, { recursive: true, force: true });

const body = friends.map((p) =>
  `  ${p.id}: {\n` +
  `    name: '${p.name}',\n` +
  `    frames: [\n` +
  p.frames.map((f) => '      [\n' + f.map((r) => `        '${r}',`).join('\n') + '\n      ],').join('\n') +
  `\n    ],\n  },`
).join('\n');

const out = `// friends.js — GENERATED by tools/import-friends.js. Do not edit by hand.
//
// Source: ${path.relative(path.join(__dirname, '..'), srcDir)}
// Re-import after editing a sprite in Aseprite:  npm run friends
//
// Each friend is one or more ${CELL}x${CELL} frames of line art: '#' ink, '.' clear.
// The drawings are the author's own; nothing here is generated or retouched.

// Wrapped: loaded as a classic <script>, a top-level const would land in the
// shared global scope and collide with sprites.js.
//
// Named FRIEND_ART, not FRIENDS: sprites.js already exports its own derived
// SPRITES.FRIENDS (id -> {name, frames, drawn}, with squash frames added for
// a friend drawn only once). This is that object's raw material -- exactly
// what was imported, nothing derived -- so the two names stay distinct.
(function () {
const FRIEND_ART = {
${body}
};

if (typeof module !== 'undefined' && module.exports) module.exports = FRIEND_ART;
if (typeof window !== 'undefined') window.FRIEND_ART = FRIEND_ART;
})();
`;

const dest = path.join(__dirname, '..', 'renderer', 'friends.js');
fs.writeFileSync(dest, out);
console.log('\nwrote ' + path.relative(path.join(__dirname, '..'), dest) + ' (' + out.length + ' bytes)');
