// lib/settings.js — load/validate/persist settings.json (SPEC.md §7).
// Takes the storage directory as a constructor argument (rather than calling
// Electron's app.getPath itself) so tests can point it at a temp dir; this
// file never imports 'electron'.
'use strict';

const fs = require('fs');
const paths = require('./paths');
// renderer/sprites.js is dual-mode (module.exports under Node, window.SPRITES
// in a renderer) specifically so this require is safe — read-only art data,
// never edited here.
const { FRIEND_IDS, FRAME_STYLES } = require('../renderer/sprites');
// renderer/background.js is generated by tools/import-bgs.js and dual-mode
// for the same reason sprites.js is — safe to require here, never edited.
const { BACKGROUND_IDS } = require('../renderer/background');
// renderer/shortcuts.js is dual-mode too, for the same reason: main.js and
// the settings window need window.SHORTCUTS, and this file needs the Node
// side of the same module rather than a second copy of the action table.
const SHORTCUTS = require('../renderer/shortcuts');

const DEFAULT_FRIEND = FRIEND_IDS[0];
const DEFAULT_FRAME_STYLE = FRAME_STYLES.includes('scallopy') ? 'scallopy' : FRAME_STYLES[0];
const DEFAULT_BACKGROUND = BACKGROUND_IDS[0];

const DEFAULTS = Object.freeze({
  focusMinutes: 25,
  shortBreakMinutes: 5,
  longBreakMinutes: 15,
  longBreakEvery: 4,
  autoStartBreaks: true,
  autoStartFocus: false,

  vaultPath: '/Users/lucabessiaristei/Documents/Opal',
  // A subfolder, not the vault root: keeps the vault tidy and avoids ever
  // colliding with Obsidian's own daily-note plugin, which can write its own
  // YYYY-MM-DD.md at the vault root. '' still means "vault root" for anyone
  // who already had that persisted before this default changed — an existing
  // settings.json keeps whatever value it already has (SPEC.md §7: missing
  // keys fall back to defaults, present ones don't), so upgrading never moves
  // or loses notes already written there.
  dailyNoteFolder: 'Pomodoro',
  dailyNoteFormat: 'YYYY-MM-DD',
  logHeading: '## Pomodoros',
  logBreaks: false,
  logAborted: false,
  loggingEnabled: true,

  friend: DEFAULT_FRIEND,
  frameStyle: DEFAULT_FRAME_STYLE,
  background: DEFAULT_BACKGROUND,
  // Off by default: a wandering pet is a visible change to the resting look
  // of every existing widget, so it's opt-in rather than switched on under
  // whoever upgrades. See renderer/widget.js petPosition().
  petMovement: false,
  // The whole palette is two colours. Everything drawn -- frame, pet, digits,
  // icons, the settings window's own chrome -- is either ink or paper, so a
  // theme is just this pair. Defaults are the original black on white; the
  // greys the settings window needs (--blush, --mute) are mixed from them at
  // render time rather than stored, so a theme can never be half-applied.
  inkColor: '#000000',
  paperColor: '#FFFFFF',
  alwaysOnTop: true,
  raiseOnEnd: true,
  scale: 2,
  opacity: 1.0,
  launchAtLogin: false,
  // Startup-only: whether the widget window shows itself on launch. A menu-bar
  // app launched at login has nowhere it "should" appear, so someone who turns
  // on launchAtLogin often wants Pomoppi to stay out of the way until they ask
  // for it. Never acted on outside of boot — see main.js createWidgetWindow.
  startHidden: false,

  soundEnabled: true,
  ringSeconds: 10,
  askForTaskName: true,

  shortcuts: SHORTCUTS.DEFAULTS,   // nested object, see renderer/shortcuts.js
});

const KEYS = Object.keys(DEFAULTS);
const BOOLEAN_KEYS = [
  'autoStartBreaks', 'autoStartFocus', 'logBreaks', 'logAborted', 'loggingEnabled',
  'alwaysOnTop', 'raiseOnEnd', 'launchAtLogin', 'startHidden', 'soundEnabled', 'askForTaskName',
  'petMovement',
];
const STRING_KEYS = ['vaultPath', 'dailyNoteFolder', 'dailyNoteFormat', 'logHeading'];
const COLOR_KEYS = ['inkColor', 'paperColor'];

// Accepts '#rgb' and '#rrggbb', with or without the '#', in either case, and
// normalises to upper-case '#RRGGBB' so every consumer can compare and blend
// without re-parsing. Anything else falls back rather than being rejected,
// same as every other value here (SPEC.md 7).
function normalizeColor(value, fallback) {
  if (typeof value !== 'string') return fallback;
  const hex = value.trim().replace(/^#/, '');
  if (/^[0-9a-fA-F]{3}$/.test(hex)) {
    return '#' + hex.split('').map((c) => c + c).join('').toUpperCase();
  }
  if (/^[0-9a-fA-F]{6}$/.test(hex)) return '#' + hex.toUpperCase();
  return fallback;
}

function clampNumber(value, min, max, fallback) {
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, n));
}

// Backs the widget's click-to-adjust controls (main.js habitsuu:adjustFocusMinutes
// / habitsuu:setLongBreakEvery). Pulled out as pure functions — rather than inline
// in the IPC handler — so they're unit-testable without requiring 'electron'.
// Their range is deliberately narrower than the settings-form range (1..180 /
// 1..12): a widget nudge is meant to stay in a sane practical band, while the
// form still accepts extremes for anyone who types them in directly.
function clampFocusAdjust(current, delta) {
  const base = Number(current);
  const start = Number.isFinite(base) ? base : DEFAULTS.focusMinutes;
  const d = Number(delta);
  const step = Number.isFinite(d) ? d : 0;
  return clampNumber(start + step, 5, 90, 5);
}

// 2..10 sessions per cycle. The upper bound is the widget's: ten 5px dots with
// 2px gaps come to exactly 68px, the width of the progress bar above them, so
// ten is the most the row can hold without outgrowing the rest of the layout.
// The lower bound is 2 because a cycle of 1 means every session earns a long
// break, which is not a cycle. Same range as validate() and the settings form.
const LONG_BREAK_EVERY_MIN = 2;
const LONG_BREAK_EVERY_MAX = 10;

function clampLongBreakEvery(value) {
  const n = Number(value);
  const start = Number.isFinite(n) ? n : DEFAULTS.longBreakEvery;
  return Math.round(clampNumber(start, LONG_BREAK_EVERY_MIN, LONG_BREAK_EVERY_MAX,
                                DEFAULTS.longBreakEvery));
}

// Backs the widget's directly-editable clock (main.js habitsuu:setFocusDuration):
// click the minutes or seconds, type digits, Enter to commit. Works in whole
// seconds rather than minutes so a typed mm:ss keeps its sub-minute precision
// instead of being rounded away — focusMinutes already tolerates a fractional
// value (it's just multiplied by 60000 to get the phase length in ms).
// Clamped to 1..90 minutes: narrower than the settings-form's 1..180, same
// reasoning as clampFocusAdjust above — a direct clock edit should stay in a
// sane practical band even though the form still accepts extremes.
function clampFocusDurationSeconds(totalSeconds) {
  return clampNumber(totalSeconds, 60, 5400, DEFAULTS.focusMinutes * 60);
}

// Drops unknown keys, fills in missing ones from defaults, clamps out-of-range
// values rather than rejecting them (SPEC.md §7).
function validate(raw) {
  const out = { ...DEFAULTS };
  if (raw && typeof raw === 'object') {
    // `friend` was called `mascot` until the rename. Read the old key so an
    // existing settings.json keeps the chosen friend instead of silently
    // reverting to the default. The next save writes it back under the new
    // name and drops the old one, so this only has to survive one write.
    if (!Object.prototype.hasOwnProperty.call(raw, 'friend') &&
        Object.prototype.hasOwnProperty.call(raw, 'mascot')) {
      out.friend = raw.mascot;
    }
    for (const key of KEYS) {
      if (Object.prototype.hasOwnProperty.call(raw, key)) out[key] = raw[key];
    }
  }

  out.focusMinutes = clampNumber(out.focusMinutes, 1, 180, DEFAULTS.focusMinutes);
  out.shortBreakMinutes = clampNumber(out.shortBreakMinutes, 1, 180, DEFAULTS.shortBreakMinutes);
  out.longBreakMinutes = clampNumber(out.longBreakMinutes, 1, 180, DEFAULTS.longBreakMinutes);
  out.longBreakEvery = clampLongBreakEvery(out.longBreakEvery);
  out.ringSeconds = clampNumber(out.ringSeconds, 0, 60, DEFAULTS.ringSeconds);
  out.opacity = clampNumber(out.opacity, 0.3, 1.0, DEFAULTS.opacity);

  const scaleNum = Number(out.scale);
  // 1x is 104x128 physical pixels -- deliberately tiny, and asked for.
  out.scale = [1, 2, 3, 4].includes(scaleNum) ? scaleNum : DEFAULTS.scale;

  out.friend = FRIEND_IDS.includes(out.friend) ? out.friend : DEFAULTS.friend;
  out.frameStyle = FRAME_STYLES.includes(out.frameStyle) ? out.frameStyle : DEFAULTS.frameStyle;
  out.background = BACKGROUND_IDS.includes(out.background) ? out.background : DEFAULTS.background;

  for (const key of COLOR_KEYS) out[key] = normalizeColor(out[key], DEFAULTS[key]);
  // Two identical colours would render an entirely blank widget -- nothing to
  // see and nothing to click back out of. Fall the pair back to the defaults.
  if (out.inkColor === out.paperColor) {
    out.inkColor = DEFAULTS.inkColor;
    out.paperColor = DEFAULTS.paperColor;
  }

  for (const key of BOOLEAN_KEYS) out[key] = Boolean(out[key]);
  for (const key of STRING_KEYS) {
    if (typeof out[key] !== 'string') out[key] = DEFAULTS[key];
  }

  out.shortcuts = SHORTCUTS.validate(out.shortcuts);

  return out;
}

class Settings {
  constructor(storageDir) {
    this.storageDir = storageDir;
    this.filePath = paths.settingsFilePath(storageDir);
    this.current = this._load();
  }

  get() {
    return { ...this.current };
  }

  set(patch) {
    // shortcuts is the schema's only nested object, so this shallow merge
    // would normally be the wrong tool -- a patch touching one key of a
    // nested object would blow away its siblings. It stays correct here only
    // because every caller that changes one binding sends the whole
    // shortcuts object back (see renderer/settings.js), never a lone key.
    const merged = { ...this.current, ...(patch && typeof patch === 'object' ? patch : {}) };
    this.current = validate(merged);
    this._persist();
    return this.get();
  }

  reset() {
    this.current = { ...DEFAULTS };
    this._persist();
    return this.get();
  }

  _load() {
    let text = null;
    try {
      text = fs.readFileSync(this.filePath, 'utf8');
    } catch (err) {
      text = null; // missing (or unreadable) file — fall back to defaults, no backup needed
    }

    let raw = null;
    if (text !== null) {
      try {
        raw = JSON.parse(text);
      } catch (err) {
        // Corrupt file: preserve it for inspection and start fresh.
        try {
          fs.renameSync(this.filePath, this.filePath + '.bak');
        } catch (_) {
          // best effort
        }
        raw = null;
      }
    }

    const validated = validate(raw);
    this.current = validated;
    this._persist();
    return validated;
  }

  _persist() {
    try {
      fs.mkdirSync(this.storageDir, { recursive: true });
      const tmp = this.filePath + '.tmp';
      fs.writeFileSync(tmp, JSON.stringify(this.current, null, 2));
      fs.renameSync(tmp, this.filePath);
    } catch (err) {
      // Best effort — in-memory settings stay usable even if persisting fails.
    }
  }
}

Settings.DEFAULTS = DEFAULTS;
Settings.clampFocusAdjust = clampFocusAdjust;
Settings.clampLongBreakEvery = clampLongBreakEvery;
// The tray's Sessions submenu enumerates this range, so it can't drift from the
// clamp the widget's dots and the settings form already share.
Settings.LONG_BREAK_EVERY_MIN = LONG_BREAK_EVERY_MIN;
Settings.LONG_BREAK_EVERY_MAX = LONG_BREAK_EVERY_MAX;
Settings.clampFocusDurationSeconds = clampFocusDurationSeconds;
Settings.normalizeColor = normalizeColor;
// Re-exported for main.js (registers the global shortcuts) and the settings
// window (renders the rebinding UI) so neither has to require renderer/shortcuts
// directly just to reach the two pieces they need.
Settings.SHORTCUT_ACTIONS = SHORTCUTS.ACTIONS;
Settings.normalizeShortcut = SHORTCUTS.normalize;

module.exports = Settings;
